### PR TITLE
Feature/fix warnings update cxf and readme

### LINKED ISSUE #8: remove compilation warnings
```
[warn] ~\git\sbt-cxf-wsdl2java\src\main\scala\io\github\borisnaguet\sbt\plugins\CxfWsdl2JavaPlugin.scala:77: `<<=` operator is deprecated. Use `key := { x.value }` or `key ~= (old => { newValue })`.
[warn] See http://www.scala-sbt.org/0.13/docs/Migrating-from-sbt-012x.html
[warn]     managedClasspath in wsdl2java <<= (classpathTypes in wsdl2java, update).map { (ct, report) =>
[warn]                                   ^
[warn] ~\git\sbt-cxf-wsdl2java\src\main\scala\io\github\borisnaguet\sbt\plugins\CxfWsdl2JavaPlugin.scala:77: `<<=` operator is deprecated. Use `key := { x.value }` or `key ~= (old => { newValue })`.
[warn] See http://www.scala-sbt.org/0.13/docs/Migrating-from-sbt-012x.html
[warn]     managedClasspath in wsdl2java <<= (classpathTypes in wsdl2java, update).map { (ct, report) =>
[warn]                                   ^
[warn] ~\git\sbt-cxf-wsdl2java\src\main\scala\io\github\borisnaguet\sbt\plugins\CxfWsdl2JavaPlugin.scala:133: `<+=` operator is deprecated. Try `lhs += { x.value }`
[warn]   or see http://www.scala-sbt.org/0.13/docs/Migrating-from-sbt-012x.html.
[warn]     sourceGenerators in Compile <+= wsdl2java
[warn]                                 ^
[warn] ~\git\sbt-cxf-wsdl2java\src\main\scala\io\github\borisnaguet\sbt\plugins\CxfWsdl2JavaPlugin.scala:133: `<+=` operator is deprecated. Try `lhs += { x.value }`
[warn]   or see http://www.scala-sbt.org/0.13/docs/Migrating-from-sbt-012x.html.
[warn]     sourceGenerators in Compile <+= wsdl2java
[warn]                                 ^
model contains 13 documentable templates
[warn] two warnings found
[info] Main Scala API documentation successful.
[info] Packaging C:\Utilisateurs\a160420\git\sbt-cxf-wsdl2java\target\scala-2.10\sbt-0.13\sbt-cxf-wsdl2java-0.2.3-SNAPSHOT-javadoc.jar ...
[warn] ~\git\sbt-cxf-wsdl2java\src\main\scala\io\github\borisnaguet\sbt\plugins\CxfWsdl2JavaPlugin.scala:77: method t2ToTable2 in object Scoped is deprecated: The sbt 0.10 style DSL is deprecated: '(k1, k2) map { (x, y) => ... }' should now be '{ val x = k1.value; val y = k2.value }'.
[warn] See http://www.scala-sbt.org/0.13/docs/Migrating-from-sbt-012x.html
[warn]     managedClasspath in wsdl2java <<= (classpathTypes in wsdl2java, update).map { (ct, report) =>
[warn]                                       ^
[info] Done packaging.
[warn] three warnings found
```

### PR DESCRIPTION
**Pull request by asollberger**
This fixes the deprecation warnings of sbt, adds a few more configuration options and some more documentation

Happy to hear what you think of it
fixes #8

### CODE REVIEW

**Comment by BorisNaguet** [comment]
Thank you very much.
I'll have a look very soon.
It relates to  #8

**Comment by asollberger** [comment]
You are most welcome.
Yes, it fixes your issue #8 
I added a comment into the pull request

**Comment by asollberger** [comment]
Sorry, pressed the wrong button

**Comment by BorisNaguet** [comment]
I've updated the develop branch to be on par with the master (so that your PR only shows the new commits), and set the version to SNAPSHOT.

**Comment by BorisNaguet** [comment]
Version 0.2..6 is released

**Comment by asollberger** [comment]
Great, thanks for merging it

**Pull request merged**
